#!/bin/bash

cd src

ENV_NAME=".clas"

if [ ! -d "$ENV_NAME" ]; then
    echo "No se encontró el entorno virtual $ENV_NAME. Creándolo..."
    
    python3 -m venv "$ENV_NAME"
    
    if [ $? -ne 0 ]; then
        echo "Error al crear el entorno virtual."
        exit 1
    fi
    
    source "$ENV_NAME/bin/activate"
    pip install --upgrade pip
    pip install matplotlib
    pip install astropy
    pip install numpy
    pip install scipy

    echo "Entorno virtual creado correctamente."
else
    echo "Cargando entorno $ENV_NAME"
    source "$ENV_NAME/bin/activate"
fi

echo ""
echo "Selecciona modo de ejecución:"
echo "1) Seleccionar periodo, descargar y clasificar"
echo "2) Seguir descargando y clasificar"
echo "3) Solamente clasificar"
echo ""

read -p "Ingresa opción (1-3): " MODO
echo ""

if [ "$MODO" = "1" ]; then
    python3 date_sel.py
fi

if [ "$MODO" = "1" ] || [ "$MODO" = "2" ]; then

    echo "Descargando archivos en las fechas seleccionadas"

    while read url; do
        echo "Procesando $url"

        wget -q -O - "$url" \
        | grep -o 'MEXICO-[^"]*\.fit\.gz' \
        | while read file; do

            full_url="${url}${file}"
            local_path="../raw_data/${file}"

            if [ -f "$local_path" ]; then
                echo "Ya existe $file, saltando"
                continue
            fi

            wget -q --show-progress --continue "$full_url" -P ../raw_data/
        done

    done < wget_list.txt
fi


python3 clasificador.py


read -p "Dirección de respaldo: " RESPALDO

if [ -n "$RESPALDO" ]; then
    rsync -avz --progress ../clas_data/ "$RESPALDO"
else
    echo "No se especificó destino de respaldo."
fi
